### ISSUE TITLE
Access to the S3

### ISSUE THREAD

**Issue by ArilessTir** [os-climate/esg-matching-pipeline#3]
Hello @patryciabp  and I can't access to the s3 bucket since today.
We have this error: 
'The AWS Access Key Id you provided does not exist in our records.'

Thank you in advance for your answer.

**Comment by HeatherAck** [comment]
Hi @ArilessTir - not sure if the s3 bucket you are referencing is OS-C's or on BNPP's side, but OS-C credentials required rotation yesterday.  You can obtain new keys from https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

**Comment by ArilessTir** [comment]
Hi Heather,
Thanks it works
